package {{ namespace }}:{{ package }};

interface {{ interface }} {
    greet: func(name: string) -> string;
}

world client {
    import {{ interface }};
}

world server {
    export {{ interface }};
}
